import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import { createPositionInferrer, type BedrockClient } from '../../services/PositionInferrer';
import {
  handler,
  type LambdaDeps,
  type GoogleOfficial,
} from '../../services/CivicDataLambda';
import type { IssueScore, LocationResult, CivicApiSuccessResponse } from '../../types';

// --- Shared generators ---

const candidateInfoArb = fc.record({
  name: fc.string({ minLength: 1, maxLength: 30 }),
  office: fc.string({ minLength: 1, maxLength: 30 }),
  bio: fc.string({ minLength: 0, maxLength: 100 }),
});

const issueArb = fc.record({
  id: fc.stringMatching(/^issue-[a-z0-9]{1,10}$/),
  text: fc.string({ minLength: 1, maxLength: 50 }),
});

const issueListArb = fc.array(issueArb, { minLength: 1, maxLength: 10 }).filter(
  // Ensure unique issue IDs
  (issues) => new Set(issues.map((i) => i.id)).size === issues.length,
);

const scoreArb: fc.Arbitrary<IssueScore> = fc.constantFrom(1 as const, -1 as const, 0 as const);

// Feature: dynamic-civic-data, Property 7: Inferred positions output validity and completeness
describe('Property 7: Inferred positions output validity and completeness', () => {
  /**
   * Validates: Requirements 3.2, 3.3
   *
   * For any candidate and any set of N issue definitions, the Position Inferrer's
   * output should contain exactly N entries (one per issue ID), and every value
   * should be exactly 1, -1, or 0.
   */
  it('output has exactly N entries with valid scores for N issues', async () => {
    await fc.assert(
      fc.asyncProperty(
        candidateInfoArb,
        issueListArb,
        async (candidate, issues) => {
          // Build a mock Bedrock response with random valid scores for each issue
          const mockScores: Record<string, IssueScore> = {};
          for (const issue of issues) {
            const scores: IssueScore[] = [1, -1, 0];
            mockScores[issue.id] = scores[Math.floor(Math.random() * 3)];
          }

          const mockClient: BedrockClient = {
            invokeModel: async () => JSON.stringify(mockScores),
          };

          const inferrer = createPositionInferrer(mockClient);
          const result = await inferrer.inferPositions(candidate, issues);

          // Verify exactly N entries
          const resultKeys = Object.keys(result);
          expect(resultKeys).toHaveLength(issues.length);

          // Verify every issue ID is present
          for (const issue of issues) {
            expect(result).toHaveProperty(issue.id);
          }

          // Verify every value is exactly 1, -1, or 0
          for (const key of resultKeys) {
            expect([1, -1, 0]).toContain(result[key]);
          }
        },
      ),
      { numRuns: 100 },
    );
  });
});

// --- Generators for Property 8 ---

const googleOfficialArb: fc.Arbitrary<GoogleOfficial> = fc.record({
  name: fc.string({ minLength: 1, maxLength: 30 }),
  office: fc.string({ minLength: 1, maxLength: 30 }),
  district: fc.string({ minLength: 1, maxLength: 20 }),
  party: fc.option(fc.string({ minLength: 1, maxLength: 20 }), { nil: undefined }),
});

const googleOfficialListArb = fc.array(googleOfficialArb, { minLength: 1, maxLength: 5 });

const locationResultArb: fc.Arbitrary<LocationResult> = fc.record({
  city: fc.string({ minLength: 1, maxLength: 20 }),
  county: fc.string({ minLength: 1, maxLength: 20 }),
  state: fc.string({ minLength: 2, maxLength: 2 }),
});

const validZipArb = fc.stringMatching(/^[0-9]{5}$/);

// Feature: dynamic-civic-data, Property 8: Inferred positions flag propagation
describe('Property 8: Inferred positions flag propagation', () => {
  /**
   * Validates: Requirements 3.4
   *
   * For any candidate whose positions were generated by the Position Inferrer,
   * the returned Candidate object should have `positionsInferred` set to `true`.
   */
  it('every candidate from the inference path has positionsInferred === true', async () => {
    await fc.assert(
      fc.asyncProperty(
        validZipArb,
        googleOfficialListArb,
        issueListArb,
        locationResultArb,
        async (zipCode, officials, issues, location) => {
          // Build mock positions response for each issue
          const mockPositions: Record<string, IssueScore> = {};
          for (const issue of issues) {
            mockPositions[issue.id] = 0;
          }

          // Mock deps: cache miss → civic client returns officials → inferrer returns positions
          const deps: LambdaDeps = {
            cache: {
              getLocation: async () => null,
              getCandidates: async () => null,
              putLocation: async () => {},
              putCandidates: async () => {},
            },
            civicClient: {
              getRepresentatives: async () => ({ location, officials }),
            },
            positionInferrer: {
              inferPositions: async () => ({ ...mockPositions }),
            },
            issues,
          };

          const response = await handler(
            { pathParameters: { zipCode } },
            deps,
          );

          expect(response.statusCode).toBe(200);

          const body: CivicApiSuccessResponse = JSON.parse(response.body);
          expect(body.candidates.length).toBe(officials.length);

          // Every candidate must have positionsInferred === true
          for (const candidate of body.candidates) {
            expect(candidate.positionsInferred).toBe(true);
          }
        },
      ),
      { numRuns: 100 },
    );
  });
});
